### ISSUE TITLE
试玩了一下，打开白屏，控制台有报错

### ISSUE THREAD

**Issue by zuisong** [zixing131/myjump#1]
<img width="719" alt="image" src="https://github.com/user-attachments/assets/697a05d4-2aa4-409f-83e1-7403e96818bf">

**Comment by zixing131** [comment]
目前在调试状态，个别游戏或者软件会报错，等后面重构就好了。

**Comment by zixing131** [comment]
另外可以勾上兼容模式，应该就不报错了，除了Anyview可能会报错

**Comment by zixing131** [comment]
最新版本已经修复此问题，可能需要刷新浏览器缓存
