### ISSUE TITLE
City Bloxx is not supported

### ISSUE THREAD

**Issue by king2015** [zixing131/myjump#2]
I like this game very much, hope you can support it.

**Comment by zixing131** [comment]
Can you provide the jar file,thank you.

**Comment by king2015** [comment]
[tower_bloxx_240x320-77975.zip](https://github.com/user-attachments/files/17088689/tower_bloxx_240x320-77975.zip)

**Comment by zixing131** [comment]
Sorry , I can not support the jar because it use the m3g module which it not support by this project now, but i can provide another jar game which is similar to this , I will upload it to the website later.
`
[都市摩天楼.zip](https://github.com/user-attachments/files/17089197/default.zip)
`

**Comment by king2015** [comment]
> Sorry , I can not support the jar because it use the m3g module which it not support by this project now, but i can provide another jar game which is similar to this , I will upload it to the website later. `[都市摩天楼.zip](https://github.com/user-attachments/files/17089197/default.zip)`

Thank you , where did you find this game that works.

**Comment by zixing131** [comment]
> > Sorry , I can not support the jar because it use the m3g module which it not support by this project now, but i can provide another jar game which is similar to this , I will upload it to the website later. `[都市摩天楼.zip](https://github.com/user-attachments/files/17089197/default.zip)`
> 
> Thank you , where did you find this game that works.

in this website https://iniche.cn/

**Comment by king2015** [comment]
> > > Sorry , I can not support the jar because it use the m3g module which it not support by this project now, but i can provide another jar game which is similar to this , I will upload it to the website later. `[都市摩天楼.zip](https://github.com/user-attachments/files/17089197/default.zip)`
> > 
> > 
> > Thank you , where did you find this game that works.
> 
> in this website https://iniche.cn/

Great, will you support games that require m3g module in the future?

**Comment by zixing131** [comment]
> > > > Sorry , I can not support the jar because it use the m3g module which it not support by this project now, but i can provide another jar game which is similar to this , I will upload it to the website later. `[都市摩天楼.zip](https://github.com/user-attachments/files/17089197/default.zip)`
> > > 
> > > 
> > > Thank you , where did you find this game that works.
> > 
> > 
> > in this website https://iniche.cn/
> 
> Great, will you support games that require m3g module in the future?

It is difficult because m3g use some native modules, if I can convert those modules to javascript ,  I will support it , it has a long way to go.
